"""Backward-compatible lazy facade; implementations live in owning modules."""
import sys
from importlib import import_module
from types import ModuleType
from typing import Any

_OWNERS = {'DAYS_AHEAD': 'run_state',
 'LOCAL_TIMEZONE': 'run_state',
 'TODAY': 'run_state',
 'END_DATE': 'run_state',
 'BONN_LAT': 'run_state',
 'BONN_LON': 'run_state',
 'MAX_RADIUS_KM': 'run_state',
 'DESCRIPTION_MAX_CHARS': 'run_state',
 '_SOURCE_CONTEXT': 'run_state',
 '_RUN_ID': 'run_state',
 '_LOGGER': 'run_state',
 '_runtime_state': 'run_state',
 'runtime_radius_km': 'run_state',
 '_BROWSER_PROFILES': 'http',
 '_BROWSER_PROFILE': 'http',
 '_TRANSIENT_HTTP_STATUSES': 'http',
 '_HTTP_RETRY_ATTEMPTS': 'run_state',
 '_HTTP_RETRY_BASE_SECONDS': 'run_state',
 '_HTTP_REQUEST_BUDGET_SECONDS': 'run_state',
 '_HTTP_RETRY_MAX_DELAY_SECONDS': 'run_state',
 '_HTTP_MAX_RESPONSE_BYTES': 'run_state',
 '_BRIGHT_DATA_API_URL': 'http',
 '_HOST_THROTTLE_SECONDS_BY_SUFFIX': 'run_state',
 '_HOST_FETCH_LOCK': 'http',
 '_HOST_LAST_FETCH_AT': 'http',
 '_HOST_SLOT_LOCK': 'http',
 '_HOST_SLOTS': 'http',
 'configure_runtime': 'run_state',
 'reset_runtime': 'run_state',
 'configure_context': 'run_state',
 'runtime_window': 'run_state',
 'runtime_days_ahead': 'run_state',
 'set_source_context': 'run_state',
 'capture_parser_metrics': 'run_state',
 '_record_parser_candidate': 'run_state',
 'log_source_disabled': 'run_state',
 'ResponseTooLargeError': 'http',
 '_HTTP_READ_CHUNK_BYTES': 'http',
 '_set_response_socket_timeout': 'http',
 '_response_read_timeout': 'http',
 '_read_response_body': 'http',
 'UnexpectedContentTypeError': 'http',
 '_record_endpoint': 'http',
 '_throttle_bucket': 'http',
 '_throttle_before_request': 'http',
 '_request_deadline': 'http',
 '_remaining_timeout': 'http',
 '_host_request_slot': 'http',
 '_sleep_for_retry': 'http',
 '_retry_delay': 'http',
 '_is_retryable_fetch_error': 'http',
 '_close_http_error': 'http',
 'browser_headers': 'http',
 'fetch_url': 'http',
 'fetch_json': 'http',
 '_raise_brightdata_failure': 'http',
 'fetch_url_with_brightdata': 'http',
 'fetch_url_with_brightdata_fallback': 'http',
 '_DETAIL_PAGE_CACHE_VERSION': 'detail_cache',
 '_DETAIL_PAGE_CACHE_DEFAULT_MAX_ENTRIES': 'detail_cache',
 '_DETAIL_PAGE_CACHE_DEFAULT_MAX_BYTES': 'detail_cache',
 '_DETAIL_PAGE_CACHE_MAX_BYTES_BY_NAMESPACE': 'detail_cache',
 '_DETAIL_PAGE_CACHE_LOCK': 'detail_cache',
 'DetailCacheEntry': 'detail_cache',
 'DetailCacheState': 'detail_cache',
 '_DETAIL_PAGE_CACHE_STATES': 'detail_cache',
 '_detail_page_cache_slug': 'detail_cache',
 '_detail_page_cache_ttl_seconds': 'detail_cache',
 '_detail_page_cache_limit': 'detail_cache',
 '_detail_page_cache_max_bytes': 'detail_cache',
 '_prune_detail_page_cache_entries': 'detail_cache',
 '_detail_page_cache_path': 'detail_cache',
 '_reset_detail_page_cache': 'detail_cache',
 '_load_detail_page_cache': 'detail_cache',
 '_persist_detail_page_cache': 'detail_cache',
 'flush_detail_page_caches': 'detail_cache',
 'fetch_detail_url': 'detail_cache',
 'parse_float': 'text',
 'post_json': 'http',
 'post_form': 'http',
 'extract_json_array': 'text',
 'clean_html': 'text',
 '_BLOCK_TAG_PATTERN': 'text',
 '_LIST_ITEM_OPEN_PATTERN': 'text',
 '_LIST_ITEM_CLOSE_PATTERN': 'text',
 '_LINE_BREAK_TAG_PATTERN': 'text',
 'clean_html_blocks': 'text',
 'normalize_block_text': 'text',
 'normalize_url': 'text',
 'is_raw_api_url': 'text',
 'normalize_venue_name': 'text',
 'GeneratedDescription': 'text',
 'description_source_for': 'text',
 '_NON_TERMINAL_ABBREVIATIONS': 'text',
 '_is_sentence_boundary': 'text',
 'concise_description': 'text',
 'factual_event_description': 'text',
 'keep_only_event_master_data': 'event_builder',
 '_CANCELLED_STATUS_WORDS': 'event_builder',
 '_CANCELLED_STATUS_SUBJECTS': 'event_builder',
 '_CANCELLED_TITLE_PATTERN': 'event_builder',
 '_CANCELLED_CONTEXT_PATTERN': 'event_builder',
 '_POSTPONED_VERLEGT_TITLE_PATTERN': 'event_builder',
 '_POSTPONED_VERLEGT_CONTEXT_PATTERN': 'event_builder',
 'has_cancelled_status': 'event_builder',
 'event_status': 'event_builder',
 'extract_dates': 'event_builder',
 'date_range_overlaps': 'event_builder',
 'in_date_range': 'event_builder',
 'window_contains': 'event_builder',
 'event_in_window': 'event_builder',
 'event_in_window_and_radius': 'event_builder',
 '_SIMPLE_TIME_PATTERN': 'text',
 '_round_time_to_quarter': 'text',
 '_format_hhmm': 'text',
 'normalize_time_fields': 'text',
 'sanitize_time_text': 'text',
 'combine_time_notes': 'text',
 '_FREE_ADMISSION_PATTERNS': 'event_builder',
 '_FREE_TITLE_PATTERN': 'event_builder',
 '_FREE_DESCRIPTION_BLOCK_PATTERN': 'event_builder',
 '_FREE_PRICE_PATTERN': 'event_builder',
 '_MUSEUM_VISITOR_ACCESS_PATTERN': 'event_builder',
 '_INFLECTED_MUSEUM_VISITOR_ACCESS_PATTERN': 'event_builder',
 '_PAID_MUSEUM_PREDICATE_PATTERN': 'event_builder',
 '_PAID_VISITOR_ACCESS_WITHOUT_AMOUNT': 'event_builder',
 '_NEGATED_PAID_VISITOR_ACCESS': 'event_builder',
 'has_paid_visitor_access': 'event_builder',
 '_has_paid_visitor_access_without_amount': 'event_builder',
 '_LIMITED_FREE_WITH_PAID_PATTERN': 'event_builder',
 '_LIMITED_FREE_CONTEXT_PATTERNS': 'event_builder',
 '_LIMITED_FREE_TRIAL_PATTERN': 'event_builder',
 '_CONDITIONAL_FREE_VISITOR_GROUP_PATTERN': 'event_builder',
 '_CONDITIONAL_FREE_ADMISSION_PATTERN': 'event_builder',
 'has_conditional_free_admission': 'event_builder',
 '_EXPLICIT_ADMISSION_SOURCE_IDS': 'event_builder',
 'source_preserves_explicit_admission': 'event_builder',
 'source_requires_pre_truncation_admission': 'event_builder',
 '_DIRECT_EXPLICIT_FREE': 'event_builder',
 '_ACTIVITY_EXPLICIT_FREE': 'event_builder',
 'has_explicit_free_admission_wording': 'event_builder',
 '_IMPLICIT_FREE_TITLE_PATTERN': 'event_builder',
 '_IMPLICIT_FREE_EXCLUSION_PATTERN': 'event_builder',
 '_VISITOR_ADMISSION_AMOUNT_PATTERN': 'event_builder',
 '_SELLER_FEE_PATTERN': 'event_builder',
 'has_seller_fee': 'event_builder',
 'infer_admission': 'event_builder',
 'infer_free_admission_price': 'event_builder',
 '_event_time_fields': 'event_builder',
 '_CANONICAL_TIME_PATTERN': 'event_builder',
 '_structured_event_times': 'event_builder',
 '_event_location': 'event_builder',
 '_QualityPreparation': 'event_builder',
 '_ICalQualityCache': 'event_builder',
 '_ICAL_QUALITY_CACHE_SIZE': 'event_builder',
 '_prepare_ical_quality': 'event_builder',
 'build_event': 'event_builder',
 'make_event': 'event_builder',
 '_legacy_is_junk_event': 'event_builder',
 'is_junk_event': 'event_builder',
 'jsonld_event_items': 'jsonld',
 '_jsonld_location': 'jsonld',
 '_jsonld_schema_token': 'jsonld',
 '_jsonld_entity_names': 'jsonld',
 '_apply_jsonld_provenance': 'jsonld',
 '_jsonld_schedule_items': 'jsonld',
 '_jsonld_schedule_dt': 'jsonld',
 '_jsonld_schedule_time_text': 'jsonld',
 '_jsonld_accessible_for_free': 'jsonld',
 '_jsonld_offer_price': 'jsonld',
 '_jsonld_offer_availability': 'jsonld',
 '_jsonld_text': 'jsonld',
 'jsonld_event_status': 'jsonld',
 '_jsonld_admission_price': 'jsonld',
 '_VISIBLE_PAID_ADMISSION_RE': 'jsonld',
 '_visible_paid_admission_price': 'jsonld',
 'events_from_jsonld': 'jsonld',
 '_ical_unfold': 'ical',
 '_ical_unescape': 'ical',
 'events_from_time_listing': 'listing_parsers',
 'events_from_ecmaps_tiles': 'listing_parsers',
 '_wp_event_manager_datetimes': 'listing_parsers',
 'events_from_wp_event_manager_listing': 'listing_parsers',
 '_ical_content_line': 'ical',
 '_ical_parse_dt': 'ical',
 '_ical_attach_event_page': 'ical',
 '_ical_feed_page': 'ical',
 '_ical_best_link': 'ical',
 '_ICAL_WEEKDAYS': 'ical',
 'index': 'ical',
 'name': 'ical',
 '_SUPPORTED_RRULE_PARTS': 'ical',
 '_ical_date_list': 'ical',
 '_ical_date_only_days': 'ical',
 '_ical_duration': 'ical',
 '_ical_recurrence_starts': 'ical',
 'fetch_ical': 'ical',
 'parse_ical': 'ical',
 'search_result_event': 'event_builder',
 'log_source_error': 'run_state',
 'log_source_quality_skip': 'run_state'}
_EXTERNAL = {'inspect': ('inspect', None),
 'json': ('json', None),
 'logging': ('logging', None),
 'os': ('os', None),
 'random': ('random', None),
 're': ('re', None),
 'threading': ('threading', None),
 'time': ('time', None),
 'urllib': ('urllib', None),
 'Callable': ('collections.abc', 'Callable'),
 'Iterator': ('collections.abc', 'Iterator'),
 'closing': ('contextlib', 'closing'),
 'contextmanager': ('contextlib', 'contextmanager'),
 'suppress': ('contextlib', 'suppress'),
 'Token': ('contextvars', 'Token'),
 'dataclass': ('dataclasses', 'dataclass'),
 'date': ('datetime', 'date'),
 'datetime': ('datetime', 'datetime'),
 'timedelta': ('datetime', 'timedelta'),
 'timezone': ('datetime', 'timezone'),
 'sha256': ('hashlib', 'sha256'),
 'unescape': ('html', 'unescape'),
 'Path': ('pathlib', 'Path'),
 'Any': ('typing', 'Any'),
 'NoReturn': ('typing', 'NoReturn'),
 'TypedDict': ('typing', 'TypedDict'),
 'ZoneInfo': ('zoneinfo', 'ZoneInfo'),
 'ZoneInfoNotFoundError': ('zoneinfo', 'ZoneInfoNotFoundError'),
 'category_taxonomy': ('.', 'category_taxonomy'),
 'config': ('.', 'config'),
 'performance': ('.', 'performance'),
 'richtext': ('.', 'richtext'),
 'MONTH_DE': ('.dates', 'MONTH_DE'),
 'MONTH_EN': ('.dates', 'MONTH_EN'),
 '_configure_date_reference': ('.dates', 'configure_reference_date'),
 'parse_date': ('.dates', 'parse_date'),
 'parse_iso_date': ('.dates', 'parse_iso_date'),
 'SourceResult': ('.health', 'SourceResult'),
 'SourceStatus': ('.health', 'SourceStatus'),
 'legacy_junk_decision': ('.junk_rules', 'legacy_junk_decision'),
 'canonicalize_city': ('.location', 'canonicalize_city'),
 'coords_for_city': ('.location', 'coords_for_city'),
 'guess_city_from_text': ('.location', 'guess_city_from_text'),
 'haversine': ('.location', 'haversine'),
 'resolve_location': ('.location', 'resolve_location'),
 'refine_bonn_location': ('.location', 'refine_bonn_location'),
 'refine_city_from_text': ('.location', 'refine_city_from_text'),
 'AdmissionDefault': ('.models', 'AdmissionDefault'),
 'EventDraft': ('.models', 'EventDraft'),
 'RawEvent': ('.models', 'RawEvent'),
 'normalize_source_id': ('.models', 'normalize_source_id'),
 'VenueResolution': ('.normalization', 'VenueResolution'),
 'resolve_venue': ('.normalization', 'resolve_venue'),
 'LOGGER_NAME': ('.observability', 'LOGGER_NAME'),
 'log': ('.observability', 'log'),
 'redact': ('.observability', 'redact'),
 'QualityDecision': ('.quality', 'QualityDecision'),
 'evaluate_event_quality': ('.quality', 'evaluate_event_quality'),
 '_RUNTIME_STATE': ('.runtime', 'ACTIVE_RUNTIME'),
 'EventWindow': ('.runtime', 'EventWindow'),
 'RunContext': ('.runtime', 'RunContext'),
 '_RuntimeState': ('.runtime', 'RuntimeState'),
 'category_score': ('.scoring', 'category_score'),
 'distance_score': ('.scoring', 'distance_score'),
 'normalize_event_title': ('.title_normalization', 'normalize_event_title')}


def __getattr__(name: str) -> Any:
    if name in _OWNERS:
        return getattr(import_module('.' + _OWNERS[name], __package__), name)
    if name in _EXTERNAL:
        module, symbol = _EXTERNAL[name]
        if module == '.' and symbol:
            return import_module('.' + symbol, __package__)
        target = import_module(module, __package__)
        return getattr(target, symbol) if symbol else target
    raise AttributeError(name)


class _Facade(ModuleType):
    """Preserve legacy monkeypatch/injection seams during adapter migration."""
    def __setattr__(self, name: str, value: Any) -> None:
        if name in _OWNERS:
            setattr(import_module('.' + _OWNERS[name], __package__), name, value)
        else:
            super().__setattr__(name, value)

    def __delattr__(self, name: str) -> None:
        if name in _OWNERS:
            delattr(import_module('.' + _OWNERS[name], __package__), name)
        else:
            super().__delattr__(name)


sys.modules[__name__].__class__ = _Facade
